%YAML:1.0
thresholdStep: 10.
minThreshold: 0.
maxThreshold: 255.
minRepeatability: 2
minDistBetweenBlobs: 10.
filterByColor: 1
blobColor: 0
filterByArea: 1
minArea: 1000.
maxArea: 500000.
filterByCircularity: 0
minCircularity: 8.0000001192092896e-01
maxCircularity: 3.4028234663852886e+38
filterByInertia: 1
minInertiaRatio: 0
maxInertiaRatio: 0.3
filterByConvexity: 1
minConvexity: 0.7
maxConvexity: 1.0
